### ISSUE TITLE
Ajustes no front-end do projeto

### ISSUE THREAD

**Issue by oliveiralex** [Paulojosep/Movie-Flix#1]
Olá Paulo, tudo bem?
Meu nome é Alexandre e eu estou corrigindo o seu trabalho. Infelizmente o mesmo não foi aceito. Abaixo vou deixar alguns pontos que eu considero importantes que você complemente o seu trabalho. Peço que você avalie e se possível faça os ajustes e reenvie o seu trabalho.

- Um dos ajustes importantes que eu considero que você faça é incluir a listagem paginada dos filmes com filtro de gênero (item 2 da especificação). Esta parte é um pré-requisito do projeto;
- Ao finalizar uma avaliação, não está exibindo o TOAST. Está na na especificação do trabalho também;
- Ao finalizar uma avaliação e visualizar a listagem de avaliações, não está exibindo o conteúdo da avaliação (ou seja, o comentário do filme).
- Sugiro algumas melhorias no layout do seu projeto. Perceba que quando você compara com o Figma, os cards estão bem maiores na altura e na largura. Eu sugiro que você utilize o recurso do box-sizing para ajustar melhor os cards na página. 

Abraço e bons estudos

**Comment by Paulojosep** [comment]
Olá @oliveiralex  tudo bem ?
Foram deitas as alterações do Move-flix
